server:
    port: 8081

spring:
    thymeleaf:
        cache: false
        enabled: true
        check-template-location: true
        encoding: UTF-8
        prefix: classpath:/templates/
        suffix: .html
        content-type: text/html
        mode: HTML5

    aop:
        auto: true
        proxy-target-class: false